### ISSUE TITLE
Vision Tower

### ISSUE THREAD

**Issue by homiec** [xiaoachen98/Open-LLaVA-NeXT#10]
I would like to ask, because open-llava-next updated clip-vit during the training process, does the open-sourced weight （ 
 https://huggingface.co/Lin-Chen/open-llava-next-vicuna-7b  ）    already include the weight of vit?

**Comment by xiaoachen98** [comment]
> I would like to ask, because open-llava-next updated clip-vit during the training process, does the open-sourced weight （ https://huggingface.co/Lin-Chen/open-llava-next-vicuna-7b ） already include the weight of vit?

Yeah. The fine-tuned weights of ViT will be auto-loaded. You can check it twice before you train the model.
