### ISSUE TITLE
Flashattention issue

### ISSUE THREAD

**Issue by LaBaZh** [xiaoachen98/Open-LLaVA-NeXT#15]
ImportError: /home/lee/.conda/envs/llava-next/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl

I encoutered this error while trying to finetune the pretrained model. This issue can be solved if i change my pytorch version from 2.1.2 to 2.0.1, but this version of torch failed to mathc the requirement and will lead to illegal access to the CUDA. Any suggestions?

High appreciate your greate work!

**Comment by JianbangZ** [comment]
try flash-attn==2.5.6
