### ISSUE TITLE
data generation code

### ISSUE THREAD

**Issue by trinhvg** [xiaoachen98/Open-LLaVA-NeXT#4]
Hello,

Thank you for your work. I am interested in creating custom instruction data and I wonder if you will release the code to obtain the data for "open-llava-next_instruct_mix1M.json"?

I have reviewed LLAVA and Instruction Tuning with GPT-4 but have not been able to find this specific information. Any assistance or references to helpful sources would be greatly appreciated.

Thank you.

**Comment by xiaoachen98** [comment]
> Hello,
> 
> Thank you for your work. I am interested in creating custom instruction data and I wonder if you will release the code to obtain the data for "open-llava-next_instruct_mix1M.json"?
> 
> I have reviewed LLAVA and Instruction Tuning with GPT-4 but have not been able to find this specific information. Any assistance or references to helpful sources would be greatly appreciated.
> 
> Thank you.

We introduce the same VQA instruction data (DocVQA, SynDog-EN, ChartQA, DVQA, AI2D, and GeoQA+) as same as llava-next. You can see the detailed information in our [Data.md](https://github.com/xiaoachen98/Open-LLaVA-NeXT/blob/master/docs/Data.md) and their [blog](https://llava-vl.github.io/blog/2024-01-30-llava-next/).
