### ISSUE TITLE
vit not saved

### ISSUE THREAD

**Issue by RifleZhang** [xiaoachen98/Open-LLaVA-NeXT#5]
It seems that vit is not saved when unfreeze_mm_vision_tower is True.

**Comment by xiaoachen98** [comment]
Actually, they will be saved in the final chenckpoint. And when you load from the checkpoint, the fine tuned vit will be re-loaded after initialization from the OpenAI version. Hope this will help you! If you like, please consider to give a star of our repo and give a like to our huggingface models (open-llava-next-8b).


---- Replied Message ----
| From | ***@***.***> |
| Date | 06/01/2024 04:34 |
| To | xiaoachen98/Open-LLaVA-NeXT ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [xiaoachen98/Open-LLaVA-NeXT] vit not saved (Issue #5) |

It seems that vit is not saved when unfreeze_mm_vision_tower is True.

**Comment by RifleZhang** [comment]
Yes. It is in saved tensors. Thanks!
